import React, { useEffect, useState } from "react";
import Head from "next/head";

// components
import MainIndex from "../components/Main/MainIndex.js";
import Tab from "../components/Main/Tab.js";

export default function Home({ props }) {
	const [search, setSearch] = useState("");
	const [nearRide, setNearRide] = useState(false);

	return (
		<div>
			<Head>
				<title>Edvora | Rides</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				{/* Tab Section */}
				<Tab
					setSearch={setSearch}
					search={search}
					props={props}
					setNearRide={setNearRide}
					nearRide={nearRide}
				/>
				{/* Box Detail Section */}
				<MainIndex props={props} search={search} nearRide={nearRide} />
			</main>
		</div>
	);
}
